[tool.poetry]
name = "pylandscape"
version = "0.1.1"
description = "Python package to explore the loss landscape of Machine Learning models"
authors = ["Tommaso Baldi"]
license = "MIT"
readme = "README.md"
homepage = "https://github.com/balditommaso/PyLandscape"
repository = "https://github.com/balditommaso/PyLandscape"
packages = [
    { include = "pylandscape" },
    { include = "pylandscape/mc_utils" }
]


[tool.poetry.dependencies]
python = ">=3.11,<3.13"
numpy = "*"
torch = "^2.10"
tqdm = "*"
brevitas = "^0.12.1"
torchvision = "^0.25.0"
pytest = "^9.0.2"
ipykernel = "^7.2.0"
scipy = "^1.17.1"
pyhessian = {git = "https://github.com/balditommaso/PyHessian.git"}


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"