save_dir: 'VGG_16_JREG_0.001'

# dataset config
data:
  name: CIFAR100DataModule
  data_path: ./data/VISION/
  num_workers: 2
  val_size: 0.1
  num_classes: 100


model:
  name: VisionModel
  size: 'baseline'
  quantization:
    verbose: 0
    input_quant: CommonIntActQuant
    first_layer_bit_width: 8
    act_channel_wise: False   # True, for mobilenet
    

fit:
  # learning rate scheduler
  lr_scheduler: cosine
  label_smoothing: 0.1
  # regularization during training
  regularizer:
    l1: 0.0
    l2: 0.0005
    jacobian: 0.001
    parseval: 0.0
  
  model_checkpoint:
    save_top_k: 1
    save_last: 0
    monitor: val_loss 
    mode: min
    auto_insert_metric_name: 0
  # PL trainer config
  trainer:
    max_epochs: 50
    accelerator: gpu
    # strategy: ddp


test:
  noise:
    path: ./data/VISION/CIFAR-100-C/CIFAR-100-C
    num_samples: 10000
    type:
      - gaussian_noise
      - impulse_noise
    severities:
      - 1
      - 2
      - 3
      - 4 
      - 5
  bit_flip:
    n_bits:
      - 1
      - 5
      - 10
      - 20
      - 50
      - 100
      - 150
      - 200
    strategy:
      - fkeras
      - random
  plot:
    min_lam: -0.3
    max_lam: 0.3
    steps: 400
  mode_connectivity:
    curve: Bezier
    num_bends: 3
    num_points: 60
    max_epochs: 50
  cka:
    batch_size: 10
    num_outputs: 10
    num_runs: 1
  hessian:
    n_iter: 100
    top_n: 1


